<?php

declare(strict_types=1);

require_once __DIR__ . '/../../vendor/autoload.php';

use Cake\Database\Connection;
use Cake\Database\Driver\Postgres;
use Quellabs\ObjectQuel\Configuration;
use Quellabs\ObjectQuel\EntityManager;

if (!extension_loaded('pdo_pgsql')) {
	throw new RuntimeException('Enable pdo_pgsql to run the PostgreSQL EQUEL smoke test.');
}

$connection = new Connection([
	'driver' => Postgres::class,
	'host' => getenv('TEST_PG_HOST') ?: '127.0.0.1',
	'port' => (int)(getenv('TEST_PG_PORT') ?: 5432),
	'username' => getenv('TEST_PG_USER') ?: 'postgres',
	'password' => getenv('TEST_PG_PASS') ?: '',
	'database' => getenv('TEST_PG_NAME') ?: 'postgres',
	'persistent' => false,
]);

$configuration = new Configuration();
$configuration->setEntityNamespace('App\\Entities');
$configuration->setEntityPath(__DIR__ . '/../../src/Entities');
$configuration->setProxyDir(sys_get_temp_dir() . '/objectquel-pg-smoke-proxies');
$entityManager = new EntityManager($configuration, $connection);
$name = 'equel_pg_smoke_' . getmypid();
$schema = $name;
$defined = [];

/**
 * @param bool $condition Result to check
 * @param string $message Failure message
 * @return void
 */
function check(bool $condition, string $message): void {
	if (!$condition) {
		throw new RuntimeException($message);
	}
}

/**
 * @param EntityManager $entityManager PostgreSQL entity manager
 * @param string $name Function name
 * @param array<string, mixed> $parameters Call arguments
 * @return mixed Function result
 */
function callValue(EntityManager $entityManager, string $name, array $parameters = []): mixed {
	$result = $entityManager->executeQuery($name . '(' . implode(', ', array_map(
		static fn(string $key): string => ':' . $key,
		array_keys($parameters)
	)) . ')', $parameters);
	check($result !== null, "Call to {$name} returned no result");
	return iterator_to_array($result)[0][$name];
}

/**
 * @param EntityManager $entityManager PostgreSQL entity manager
 * @param list<string> $defined Names to remove during cleanup
 * @param string $name Function name
 * @param string $source Function signature and body
 * @return void
 */
function defineRoutine(EntityManager $entityManager, array &$defined, string $name, string $source): void {
	$entityManager->executeQuery("define function {$name} {$source}");
	$defined[] = $name;
}

$connection->execute('CREATE SCHEMA "' . $schema . '"');
$connection->execute('SET search_path TO "' . $schema . '", public');
$connection->execute('CREATE TABLE users (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, banned BOOLEAN NOT NULL DEFAULT FALSE)');
$connection->execute('INSERT INTO users (username, password, banned) VALUES (:username, :password, FALSE)', ['username' => $name, 'password' => 'pw']);
$row = $connection->execute('SELECT id FROM users WHERE username = :username', ['username' => $name])?->fetch('assoc');
check(is_array($row), 'Could not insert the PostgreSQL fixture');
$id = (int)$row['id'];

try {
	$double = $name . '_double';
	defineRoutine($entityManager, $defined, $double, '(int n) integer { return n * 2 }');
	check(callValue($entityManager, $double, ['n' => 21]) === 42, 'Standalone function call failed');
	$positive = $name . '_positive';
	defineRoutine($entityManager, $defined, $positive, '(int n) boolean { return n > 0 }');
	check(callValue($entityManager, $positive, ['n' => 1]) === true, 'Boolean return conversion failed');
	check(callValue($entityManager, $positive, ['n' => -1]) === false, 'False return conversion failed');

	try {
		$entityManager->executeQuery("define function {$double} (int n) integer { return n * 3 }");
		throw new RuntimeException('Redefining a function unexpectedly succeeded');
	} catch (\Quellabs\ObjectQuel\Exception\QuelException $exception) {
		check(str_contains($exception->getMessage(), 'already exists'), 'Duplicate definition returned the wrong error');
	}
	check(callValue($entityManager, $double, ['n' => 21]) === 42, 'Duplicate definition changed the existing function');

	$outer = $name . '_outer';
	defineRoutine($entityManager, $defined, $outer, "(int n) integer { return {$double}(n) + 1 }");
	check(callValue($entityManager, $outer, ['n' => 21]) === 43, 'Nested function call failed');

	$result = $entityManager->executeQuery("range of u is UserEntity retrieve (n = {$double}(u.id)) where u.id = :id", ['id' => $id]);
	check($result !== null && (int)$result[0]['n'] === $id * 2, 'Function call in a query failed');

	$count = $name . '_count';
	defineRoutine($entityManager, $defined, $count, '(int minId) integer {
		integer total = 0
		range of u is UserEntity
		cursor users = retrieve (u.id) where u.id >= minId
		foreach users { total++ }
		return total
	}');
	check(callValue($entityManager, $count, ['minId' => $id]) >= 1, 'Cursor loop failed');

	$suffix = $name . '_suffix';
	defineRoutine($entityManager, $defined, $suffix, '(string s) string { return concat(s, "!") }');
	$rename = $name . '_rename';
	defineRoutine($entityManager, $defined, $rename, '(int uid, string who) void {
		range of u is UserEntity
		replace u (username = who) where u.id = uid
	}');
	$renameOuter = $name . '_rename_outer';
	defineRoutine($entityManager, $defined, $renameOuter, "(int uid) void {
		range of u is UserEntity
		cursor users = retrieve (u.id, name = {$suffix}(u.username)) where u.id = uid
		foreach users { {$rename}(users.id, users.name) }
	}");
	$entityManager->executeQuery("{$renameOuter}(:id)", ['id' => $id]);
	check((string)$connection->execute('SELECT username FROM users WHERE id = :id', ['id' => $id])?->fetch('assoc')['username'] === $name . '!', 'Procedure call in a cursor failed');
	$renameByFunction = $name . '_rename_by_function';
	defineRoutine($entityManager, $defined, $renameByFunction, "(int uid) integer { {$rename}(uid, \"called from function\") return uid }");
	check(callValue($entityManager, $renameByFunction, ['uid' => $id]) === $id, 'Function calling a procedure failed');
	check((string)$connection->execute('SELECT username FROM users WHERE id = :id', ['id' => $id])?->fetch('assoc')['username'] === 'called from function', 'Procedure called by a function did not write');

	$atomic = $name . '_atomic';
	defineRoutine($entityManager, $defined, $atomic, '(int uid, int cancel) void {
		range of u is UserEntity
		begin transaction {
			replace u (banned = true) where u.id = uid
			if (cancel = 1) { abort }
		}
	}');
	$connection->begin();
	try {
		$connection->execute('UPDATE users SET banned = FALSE WHERE id = :id', ['id' => $id]);
		$entityManager->executeQuery("{$atomic}(:id, 1)", ['id' => $id]);
		check($connection->execute('SELECT banned FROM users WHERE id = :id', ['id' => $id])?->fetch('assoc')['banned'] === false, 'Abort did not roll back the atomic block');
		$entityManager->executeQuery("{$atomic}(:id, 0)", ['id' => $id]);
		check($connection->execute('SELECT banned FROM users WHERE id = :id', ['id' => $id])?->fetch('assoc')['banned'] === true, 'Atomic block success did not preserve its write');
	} finally {
		$connection->rollback();
	}
	check($connection->execute('SELECT banned FROM users WHERE id = :id', ['id' => $id])?->fetch('assoc')['banned'] === false, 'Atomic block committed the caller transaction');
	$entityManager->executeQuery("{$atomic}(:id, 0)", ['id' => $id]);
	check($connection->execute('SELECT banned FROM users WHERE id = :id', ['id' => $id])?->fetch('assoc')['banned'] === true, 'Standalone atomic call did not commit');
	$connection->execute('UPDATE users SET banned = FALSE WHERE id = :id', ['id' => $id]);

	$connection->execute('INSERT INTO users (username, password) VALUES (:username, :password)', ['username' => 'duplicate_' . $name, 'password' => 'pw']);
	$error = $name . '_error';
	defineRoutine($entityManager, $defined, $error, '(int uid, string duplicateName) void {
		range of u is UserEntity
		begin transaction {
			replace u (banned = true) where u.id = uid
			replace u (username = duplicateName) where u.id = uid
		}
	}');
	try {
		$entityManager->executeQuery("{$error}(:id, :who)", ['id' => $id, 'who' => 'duplicate_' . $name]);
		throw new RuntimeException('Unique violation in atomic block unexpectedly succeeded');
	} catch (Throwable $exception) {
		check(!($exception instanceof RuntimeException && $exception->getMessage() === 'Unique violation in atomic block unexpectedly succeeded'), 'Unique violation was not propagated');
	}
	check($connection->execute('SELECT banned FROM users WHERE id = :id', ['id' => $id])?->fetch('assoc')['banned'] === false, 'Database error did not roll back the atomic block');

	$entityManager->executeQuery("destroy function {$outer}");
	$defined = array_values(array_diff($defined, [$outer]));
	check(callValue($entityManager, $double, ['n' => 3]) === 6, 'Destroy function removed the wrong function');
	echo "PostgreSQL EQUEL smoke test passed\n";
} finally {
	foreach (array_reverse($defined) as $routine) {
		try {
			$entityManager->executeQuery("destroy function {$routine} if exists");
		} catch (Throwable $exception) {
			fwrite(STDERR, "Cleanup failed for {$routine}: {$exception->getMessage()}\n");
		}
	}
	$connection->execute('DROP SCHEMA "' . $schema . '" CASCADE');
}
