<?php

declare(strict_types=1);

require_once __DIR__ . '/../vendor/autoload.php';

use Cake\Database\Connection;
use Cake\Database\Driver\Postgres;
use Quellabs\ObjectQuel\Configuration;
use Quellabs\ObjectQuel\EntityManager;

if (!extension_loaded('pdo_pgsql')) {
	throw new RuntimeException('The PostgreSQL test suite requires pdo_pgsql.');
}

$connection = new Connection([
	'driver' => Postgres::class,
	'host' => getenv('TEST_PG_HOST') ?: '127.0.0.1',
	'port' => (int)(getenv('TEST_PG_PORT') ?: 5432),
	'username' => getenv('TEST_PG_USER') ?: 'postgres',
	'password' => getenv('TEST_PG_PASS') ?: '',
	'database' => getenv('TEST_PG_NAME') ?: 'postgres',
	'persistent' => false,
]);

$schema = 'objectquel_test_' . getmypid();
$connection->execute('CREATE SCHEMA "' . $schema . '"');
$connection->execute('SET search_path TO "' . $schema . '", public');
$connection->execute('CREATE TABLE users (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, banned BOOLEAN NOT NULL DEFAULT FALSE)');
$connection->execute('CREATE TABLE posts (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(255) NOT NULL, user_id INTEGER NOT NULL, deleted_at TIMESTAMP NULL)');
$connection->execute("INSERT INTO users (username, password, banned) VALUES ('alice', 'pw', FALSE), ('bob', 'pw', FALSE), ('charlie', 'pw', FALSE)");

$configuration = new Configuration();
$configuration->setEntityNamespace('App\\Entities');
$configuration->setEntityPath(__DIR__ . '/../src/Entities');
$configuration->setProxyDir(sys_get_temp_dir() . '/objectquel-pg-phpunit-proxies');
$GLOBALS['test_em'] = new EntityManager($configuration, $connection);
$GLOBALS['test_connection'] = $connection;

register_shutdown_function(static function () use ($connection, $schema): void {
	$connection->rollback();
	$connection->execute('DROP SCHEMA IF EXISTS "' . $schema . '" CASCADE');
});
