<?php

	namespace Quellabs\ObjectQuel\Tests\Unit;

	use PHPUnit\Framework\TestCase;
	use Quellabs\ObjectQuel\ObjectQuel\Ast\AstCreateTable;
	use Quellabs\ObjectQuel\ObjectQuel\Lexer;
	use Quellabs\ObjectQuel\ObjectQuel\Parser;
	use Quellabs\ObjectQuel\ObjectQuel\QuelToSQLCreate;
	use Quellabs\ObjectQuel\Tests\Support\FakePlatformCapabilities;

	/**
	 * Dialect-level coverage for QuelToSQLCreate. The suite's only live
	 * connection (see tests/Integration/CreateTableTest) is MySQL, so this is
	 * the only place mysql/pgsql/sqlite/sqlsrv generated SQL is actually
	 * compared — in particular the SQL-Server-specific `if not exists`
	 * existence-check wrapper, never otherwise exercised.
	 */
	class QuelToSQLCreateTest extends TestCase {

		private function parse(string $query): AstCreateTable {
			$ast = (new Parser(new Lexer($query)))->parse();
			self::assertInstanceOf(AstCreateTable::class, $ast);
			return $ast;
		}

		private function compile(AstCreateTable $ast, string $dialect): string {
			return (new QuelToSQLCreate(new FakePlatformCapabilities($dialect)))->convertToSQL($ast);
		}

		public function testPermanentTableAcrossDialects(): void {
			$ast = $this->parse('create Foo (id = integer)');

			self::assertSame('CREATE TABLE `Foo` (`id` INT)', $this->compile($ast, 'mysql'));
			self::assertSame('CREATE TABLE "Foo" ("id" INTEGER)', $this->compile($ast, 'pgsql'));
			self::assertSame('CREATE TABLE `Foo` (`id` INTEGER)', $this->compile($ast, 'sqlite'));
			self::assertSame('CREATE TABLE [Foo] ([id] INT)', $this->compile($ast, 'sqlsrv'));
		}

		public function testTemporaryTableAcrossDialects(): void {
			$ast = $this->parse('create temporary Foo (id = integer)');

			self::assertSame('CREATE TEMPORARY TABLE `Foo` (`id` INT)', $this->compile($ast, 'mysql'));
			self::assertSame('CREATE TEMPORARY TABLE "Foo" ("id" INTEGER)', $this->compile($ast, 'pgsql'));
			self::assertSame('CREATE TEMPORARY TABLE `Foo` (`id` INTEGER)', $this->compile($ast, 'sqlite'));

			// SQL Server has no CREATE TEMPORARY TABLE keyword — temp-ness
			// comes from the '#' prefix in the physical name instead.
			self::assertSame('CREATE TABLE [#Foo] ([id] INT)', $this->compile($ast, 'sqlsrv'));
		}

		public function testIfNotExistsIsInlineOnEveryDialectExceptSqlServer(): void {
			$ast = $this->parse('create Foo (id = integer) if not exists');

			self::assertSame('CREATE TABLE IF NOT EXISTS `Foo` (`id` INT)', $this->compile($ast, 'mysql'));
			self::assertSame('CREATE TABLE IF NOT EXISTS "Foo" ("id" INTEGER)', $this->compile($ast, 'pgsql'));
			self::assertSame('CREATE TABLE IF NOT EXISTS `Foo` (`id` INTEGER)', $this->compile($ast, 'sqlite'));
		}

		public function testIfNotExistsWithTemporaryIsInlineOnEveryDialectExceptSqlServer(): void {
			$ast = $this->parse('create temporary Foo (id = integer) if not exists');

			self::assertSame('CREATE TEMPORARY TABLE IF NOT EXISTS `Foo` (`id` INT)', $this->compile($ast, 'mysql'));
			self::assertSame('CREATE TEMPORARY TABLE IF NOT EXISTS "Foo" ("id" INTEGER)', $this->compile($ast, 'pgsql'));
			self::assertSame('CREATE TEMPORARY TABLE IF NOT EXISTS `Foo` (`id` INTEGER)', $this->compile($ast, 'sqlite'));
		}

		public function testIfNotExistsWrapsInAnExistenceCheckOnSqlServer(): void {
			$ast = $this->parse('create Foo (id = integer) if not exists');

			self::assertSame(
				"IF OBJECT_ID(N'Foo', N'U') IS NULL CREATE TABLE [Foo] ([id] INT)",
				$this->compile($ast, 'sqlsrv')
			);
		}

		public function testIfNotExistsWithTemporaryOnSqlServerChecksTempdb(): void {
			$ast = $this->parse('create temporary Foo (id = integer) if not exists');

			self::assertSame(
				"IF OBJECT_ID('tempdb..#Foo') IS NULL CREATE TABLE [#Foo] ([id] INT)",
				$this->compile($ast, 'sqlsrv')
			);
		}

		public function testColumnConstraintsAcrossDialects(): void {
			$ast = $this->parse('create Foo (id = integer identity primary key, name = string(50) not null)');

			self::assertSame(
				'CREATE TABLE `Foo` (`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(50) NOT NULL)',
				$this->compile($ast, 'mysql')
			);
			self::assertSame(
				'CREATE TABLE "Foo" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "name" VARCHAR(50) NOT NULL)',
				$this->compile($ast, 'pgsql')
			);
			self::assertSame(
				'CREATE TABLE `Foo` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `name` VARCHAR(50) NOT NULL)',
				$this->compile($ast, 'sqlite')
			);
			self::assertSame(
				'CREATE TABLE [Foo] ([id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, [name] VARCHAR(50) NOT NULL)',
				$this->compile($ast, 'sqlsrv')
			);
		}
	}
