<?php

	namespace Quellabs\ObjectQuel\Tests\Unit;

	use PHPUnit\Framework\TestCase;
	use Quellabs\ObjectQuel\ObjectQuel\Ast\AstCreateTable;
	use Quellabs\ObjectQuel\ObjectQuel\Lexer;
	use Quellabs\ObjectQuel\ObjectQuel\Parser;
	use Quellabs\ObjectQuel\ObjectQuel\ParserException;
	use Quellabs\ObjectQuel\ObjectQuel\QuelToSQLCreate;
	use Quellabs\ObjectQuel\Tests\Support\FakePlatformCapabilities;

	/**
	 * Dialect-level coverage for QuelToSQLCreate. The suite's only live
	 * connection (see tests/Integration/CreateTableTest) is MySQL, so this is
	 * the only place mysql/pgsql/sqlite/sqlsrv generated SQL is actually
	 * compared — in particular the SQL-Server-specific `if not exists`
	 * existence-check wrapper, never otherwise exercised.
	 */
	class QuelToSQLCreateTest extends TestCase {

		private function parse(string $query): AstCreateTable {
			$ast = (new Parser(new Lexer($query), $GLOBALS['test_em']->getEntityStore()))->parse();
			self::assertInstanceOf(AstCreateTable::class, $ast);
			return $ast;
		}

		private function compile(AstCreateTable $ast, string $dialect): string {
			return (new QuelToSQLCreate(new FakePlatformCapabilities($dialect)))->convertToSQL($ast);
		}

		public function testPermanentTableAcrossDialects(): void {
			$ast = $this->parse('create Foo (id = integer)');

			self::assertSame('CREATE TABLE `Foo` (`id` INT)', $this->compile($ast, 'mysql'));
			self::assertSame('CREATE TABLE "Foo" ("id" INTEGER)', $this->compile($ast, 'pgsql'));
			self::assertSame('CREATE TABLE `Foo` (`id` INTEGER)', $this->compile($ast, 'sqlite'));
			self::assertSame('CREATE TABLE [Foo] ([id] INT)', $this->compile($ast, 'sqlsrv'));
		}

		public function testTemporaryTableAcrossDialects(): void {
			$ast = $this->parse('create temporary Foo (id = integer)');

			self::assertSame('CREATE TEMPORARY TABLE `Foo` (`id` INT)', $this->compile($ast, 'mysql'));
			self::assertSame('CREATE TEMPORARY TABLE "Foo" ("id" INTEGER)', $this->compile($ast, 'pgsql'));
			self::assertSame('CREATE TEMPORARY TABLE `Foo` (`id` INTEGER)', $this->compile($ast, 'sqlite'));

			// SQL Server has no CREATE TEMPORARY TABLE keyword — temp-ness
			// comes from the '#' prefix in the physical name instead.
			self::assertSame('CREATE TABLE [#Foo] ([id] INT)', $this->compile($ast, 'sqlsrv'));
		}

		public function testIfNotExistsIsInlineOnEveryDialectExceptSqlServer(): void {
			$ast = $this->parse('create Foo (id = integer) if not exists');

			self::assertSame('CREATE TABLE IF NOT EXISTS `Foo` (`id` INT)', $this->compile($ast, 'mysql'));
			self::assertSame('CREATE TABLE IF NOT EXISTS "Foo" ("id" INTEGER)', $this->compile($ast, 'pgsql'));
			self::assertSame('CREATE TABLE IF NOT EXISTS `Foo` (`id` INTEGER)', $this->compile($ast, 'sqlite'));
		}

		public function testIfNotExistsWithTemporaryIsInlineOnEveryDialectExceptSqlServer(): void {
			$ast = $this->parse('create temporary Foo (id = integer) if not exists');

			self::assertSame('CREATE TEMPORARY TABLE IF NOT EXISTS `Foo` (`id` INT)', $this->compile($ast, 'mysql'));
			self::assertSame('CREATE TEMPORARY TABLE IF NOT EXISTS "Foo" ("id" INTEGER)', $this->compile($ast, 'pgsql'));
			self::assertSame('CREATE TEMPORARY TABLE IF NOT EXISTS `Foo` (`id` INTEGER)', $this->compile($ast, 'sqlite'));
		}

		public function testIfNotExistsWrapsInAnExistenceCheckOnSqlServer(): void {
			$ast = $this->parse('create Foo (id = integer) if not exists');

			self::assertSame(
				"IF OBJECT_ID(N'Foo', N'U') IS NULL CREATE TABLE [Foo] ([id] INT)",
				$this->compile($ast, 'sqlsrv')
			);
		}

		public function testIfNotExistsWithTemporaryOnSqlServerChecksTempdb(): void {
			$ast = $this->parse('create temporary Foo (id = integer) if not exists');

			self::assertSame(
				"IF OBJECT_ID('tempdb..#Foo') IS NULL CREATE TABLE [#Foo] ([id] INT)",
				$this->compile($ast, 'sqlsrv')
			);
		}

		public function testColumnConstraintsAcrossDialects(): void {
			$ast = $this->parse('create Foo (id = integer identity, name = string(50) not null, primary key (id))');

			self::assertSame(
				'CREATE TABLE `Foo` (`id` INT NOT NULL AUTO_INCREMENT, `name` VARCHAR(50) NOT NULL, PRIMARY KEY (`id`))',
				$this->compile($ast, 'mysql')
			);
			self::assertSame(
				'CREATE TABLE "Foo" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY, "name" VARCHAR(50) NOT NULL, PRIMARY KEY ("id"))',
				$this->compile($ast, 'pgsql')
			);
			self::assertSame(
				'CREATE TABLE `Foo` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `name` VARCHAR(50) NOT NULL)',
				$this->compile($ast, 'sqlite')
			);
			self::assertSame(
				'CREATE TABLE [Foo] ([id] INT IDENTITY(1,1) NOT NULL, [name] VARCHAR(50) NOT NULL, PRIMARY KEY ([id]))',
				$this->compile($ast, 'sqlsrv')
			);
		}

		/**
		 * `unsigned` precedes the type name, matching C's `unsigned int` order
		 * rather than MySQL's inline `INT UNSIGNED` suffix. It's a
		 * MySQL/MariaDB-only DDL concept — the other three dialects have no
		 * UNSIGNED syntax, so PlatformCapabilitiesInterface::
		 * supportsUnsignedIntegers() being false there means the modifier is
		 * silently dropped rather than appearing in their rendered SQL (see
		 * DDLTypeMapper::getMysqlTempTableColumnType()).
		 */
		public function testUnsignedIsRenderedOnlyOnMysql(): void {
			$ast = $this->parse('create Foo (count = unsigned integer not null)');

			self::assertSame('CREATE TABLE `Foo` (`count` INT UNSIGNED NOT NULL)', $this->compile($ast, 'mysql'));
			self::assertSame('CREATE TABLE "Foo" ("count" INTEGER NOT NULL)', $this->compile($ast, 'pgsql'));
			self::assertSame('CREATE TABLE `Foo` (`count` INTEGER NOT NULL)', $this->compile($ast, 'sqlite'));
			self::assertSame('CREATE TABLE [Foo] ([count] INT NOT NULL)', $this->compile($ast, 'sqlsrv'));
		}

		/**
		 * Bare `unsigned` with no type name defaults to `integer`, mirroring
		 * C's `unsigned` being shorthand for `unsigned int`.
		 */
		public function testBareUnsignedDefaultsToInteger(): void {
			$ast = $this->parse('create Foo (count = unsigned not null)');

			self::assertSame('CREATE TABLE `Foo` (`count` INT UNSIGNED NOT NULL)', $this->compile($ast, 'mysql'));
		}

		/**
		 * `unsigned` on a type that can never be signed/unsigned in the first
		 * place (e.g. `string`) is a genuine authoring mistake, rejected at
		 * parse time regardless of target engine — unlike an engine simply
		 * lacking UNSIGNED support (see testUnsignedIsRenderedOnlyOnMysql()),
		 * which is not an error.
		 */
		public function testUnsignedOnANonNumericTypeIsRejectedAtParseTime(): void {
			$this->expectException(ParserException::class);
			$this->expectExceptionMessage("Column 'name' declares 'unsigned' but type 'string' does not support it");

			$this->parse('create Foo (name = unsigned string(50))');
		}

		/**
		 * A composite PK never triggers SQLite's inline AUTOINCREMENT idiom
		 * (that's reserved for the single-column identity case) — every
		 * dialect renders the same trailing PRIMARY KEY (...) table
		 * constraint, with each member column forced effectively NOT NULL
		 * even though neither declares it explicitly.
		 */
		public function testCompositePrimaryKeyAcrossDialects(): void {
			$ast = $this->parse('create Bridge (post_id = integer, tag_id = integer, primary key (post_id, tag_id))');

			self::assertSame(
				'CREATE TABLE `Bridge` (`post_id` INT NOT NULL, `tag_id` INT NOT NULL, PRIMARY KEY (`post_id`, `tag_id`))',
				$this->compile($ast, 'mysql')
			);
			self::assertSame(
				'CREATE TABLE "Bridge" ("post_id" INTEGER NOT NULL, "tag_id" INTEGER NOT NULL, PRIMARY KEY ("post_id", "tag_id"))',
				$this->compile($ast, 'pgsql')
			);
			self::assertSame(
				'CREATE TABLE `Bridge` (`post_id` INTEGER NOT NULL, `tag_id` INTEGER NOT NULL, PRIMARY KEY (`post_id`, `tag_id`))',
				$this->compile($ast, 'sqlite')
			);
			self::assertSame(
				'CREATE TABLE [Bridge] ([post_id] INT NOT NULL, [tag_id] INT NOT NULL, PRIMARY KEY ([post_id], [tag_id]))',
				$this->compile($ast, 'sqlsrv')
			);
		}
	}
