<?php
	
	namespace Quellabs\Canvas\Loom;
	
	/**
	 * Holds the result of rendering a single node.
	 * Collects both the rendered HTML and any WakaPAC initialisation scripts
	 * generated by the node or its descendants. Scripts are accumulated
	 * bottom-up through the tree and flushed as a single inline script block
	 * at the end of the render pass.
	 */
	class RenderResult {
		
		/** @var string Rendered HTML for this node and all its descendants */
		public string $html;
		
		/** @var array WakaPAC initialisation scripts collected from this node and its descendants */
		public array $scripts;
		
		/**
		 * @param string $html    Rendered HTML
		 * @param array  $scripts WakaPAC initialisation scripts, if any
		 */
		public function __construct(string $html, array $scripts = []) {
			$this->html    = $html;
			$this->scripts = $scripts;
		}
	}